#!/bin/sh

# Prevents force pushes and deletions of protected branches (main and master).
#
# If this script exits with a non-zero status nothing will be pushed.
#
# Protected commands that will be blocked:
#   git push --force origin main
#   git push --delete origin main
#   git push origin :main
#   (same for master)
#
# Nor will a force push while on a protected branch be allowed:
#   git co main
#   git push --force origin

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
push_command=$(ps -ocommand= -p $PPID)
is_destructive='force|delete|\-f'

do_exit(){
  echo "[Policy] Never force push or delete the $1 branch! (Prevented with pre-push hook.)"
  exit 1
}

for protected_branch in main master; do
  will_remove_protected=":$protected_branch"

  if [[ $push_command =~ $is_destructive ]] && [ "$current_branch" = "$protected_branch" ]; then
    do_exit "$protected_branch"
  fi

  if [[ $push_command =~ $is_destructive ]] && [[ $push_command =~ $protected_branch ]]; then
    do_exit "$protected_branch"
  fi

  if [[ $push_command =~ $will_remove_protected ]]; then
    do_exit "$protected_branch"
  fi
done

exit 0
